packages:
  - "packages/core"
  - "packages/drivers"
  - "packages/drivers/*"
  - "packages/plugins"
  - "packages/plugins/*"
  - "examples/*"
  - "examples/remix/*"

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
