const DECODER_IP = "10.0.2.15";

// prettier-ignore
const config = {"encoders": [
{"name": "Puss Gets The Boot",         "uri" :  `udp://239.0.0.1:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Midnight Snack",         "uri" :  `udp://239.0.0.2:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Night Before Christmas", "uri" :  `udp://239.0.0.3:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Fraidy Cat",                 "uri" :  `udp://239.0.0.4:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Dog Trouble",                "uri" :  `udp://239.0.0.5:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Puss N' Toots",              "uri" :  `udp://239.0.0.6:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Bowling Alley-Cat",      "uri" :  `udp://239.0.0.7:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Fine Feathered Friend",      "uri" :  `udp://239.0.0.8:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Sufferin' Cats!",            "uri" :  `udp://239.0.0.9:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Lonesome Mouse",         "uri" : `udp://239.0.0.10:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Yankee Doodle Mouse",    "uri" : `udp://239.0.0.11:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Baby Puss",                  "uri" : `udp://239.0.0.12:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Zoot Cat",               "uri" : `udp://239.0.0.13:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Million Dollar Cat",     "uri" : `udp://239.0.0.14:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Bodyguard",              "uri" : `udp://239.0.0.15:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Puttin' On The Dog",         "uri" : `udp://239.0.0.16:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Mouse Trouble",              "uri" : `udp://239.0.0.17:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "The Mouse Comes To Dinner",  "uri" : `udp://239.0.0.18:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Mouse In Manhattan",         "uri" : `udp://239.0.0.19:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
{"name": "Tee For Two",                "uri" : `udp://239.0.0.20:1234?pkt_size=1316&localaddr=${DECODER_IP}` } ,
]
}

export default config;

// {"name": "Flirty Birdy", "uri": "/home/anon/videos/Tom and Jerry/S1940E21 - Flirty Birdy.mkv"},
// {"name": "Quiet Please!", "uri": "/home/anon/videos/Tom and Jerry/S1940E22 - Quiet Please!.mkv"},
// {"name": "Springtime For Thomas", "uri": "/home/anon/videos/Tom and Jerry/S1940E23 - Springtime For Thomas.mkv"},
// {"name": "The Milky Waif", "uri": "/home/anon/videos/Tom and Jerry/S1940E24 - The Milky Waif.mkv"},
// {"name": "Trap Happy", "uri": "/home/anon/videos/Tom and Jerry/S1940E25 - Trap Happy.mkv"},
// {"name": "Solid Serenade", "uri": "/home/anon/videos/Tom and Jerry/S1940E26 - Solid Serenade.mkv"},
// {"name": "Cat Fishin'", "uri": "/home/anon/videos/Tom and Jerry/S1940E27 - Cat Fishin'.mkv"},
// {"name": "Part Time Pal", "uri": "/home/anon/videos/Tom and Jerry/S1940E28 - Part Time Pal.mkv"},
// {"name": "The Cat Concerto", "uri": "/home/anon/videos/Tom and Jerry/S1940E29 - The Cat Concerto.mkv"},
// {"name": "Dr", "uri": "/home/anon/videos/Tom and Jerry/S1940E30 - Dr. Jekyll and Mr. Mouse.mkv"},
// {"name": "Salt Water Tabby", "uri": "/home/anon/videos/Tom and Jerry/S1940E31 - Salt Water Tabby.mkv"},
// {"name": "A Mouse In The House", "uri": "/home/anon/videos/Tom and Jerry/S1940E32 - A Mouse In The House.mkv"},
// {"name": "The Invisible Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1940E33 - The Invisible Mouse.mkv"},
// {"name": "Kitty Foiled", "uri": "/home/anon/videos/Tom and Jerry/S1940E34 - Kitty Foiled.mkv"},
// {"name": "The Truce Hurts", "uri": "/home/anon/videos/Tom and Jerry/S1940E35 - The Truce Hurts.mkv"},
// {"name": "Old Rockin' Chair Tom", "uri": "/home/anon/videos/Tom and Jerry/S1940E36 - Old Rockin' Chair Tom.mkv"},
// {"name": "Professor Tom", "uri": "/home/anon/videos/Tom and Jerry/S1940E37 - Professor Tom.mkv"},
// {"name": "Mouse Cleaning", "uri": "/home/anon/videos/Tom and Jerry/S1940E38 - Mouse Cleaning.mkv"},
// {"name": "Polka-Dot Puss", "uri": "/home/anon/videos/Tom and Jerry/S1940E39 - Polka-Dot Puss.mkv"},
// {"name": "The Little Orphan", "uri": "/home/anon/videos/Tom and Jerry/S1940E40 - The Little Orphan.mkv"},
// {"name": "Hatch Up Your Troubles", "uri": "/home/anon/videos/Tom and Jerry/S1940E41 - Hatch Up Your Troubles.mkv"},
// {"name": "Heavenly Puss", "uri": "/home/anon/videos/Tom and Jerry/S1940E42 - Heavenly Puss.mkv"},
// {"name": "The Cat And The Mermouse", "uri": "/home/anon/videos/Tom and Jerry/S1940E43 - The Cat And The Mermouse.mkv"},
// {"name": "Love That Pup", "uri": "/home/anon/videos/Tom and Jerry/S1940E44 - Love That Pup.mkv"},
// {"name": "Jerry's Diary", "uri": "/home/anon/videos/Tom and Jerry/S1940E45 - Jerry's Diary.mkv"},
// {"name": "Tennis Chumps", "uri": "/home/anon/videos/Tom and Jerry/S1940E46 - Tennis Chumps.mkv"},
// {"name": "Little Quacker", "uri": "/home/anon/videos/Tom and Jerry/S1950E01 - Little Quacker.mkv"},
// {"name": "Saturday Evening Puss", "uri": "/home/anon/videos/Tom and Jerry/S1950E02 - Saturday Evening Puss.mkv"},
// {"name": "Texas Tom", "uri": "/home/anon/videos/Tom and Jerry/S1950E03 - Texas Tom.mkv"},
// {"name": "Jerry And The Lion", "uri": "/home/anon/videos/Tom and Jerry/S1950E04 - Jerry And The Lion.mkv"},
// {"name": "Safety Second", "uri": "/home/anon/videos/Tom and Jerry/S1950E05 - Safety Second.mkv"},
// {"name": "Tom and Jerry in the Hollywood Bowl", "uri": "/home/anon/videos/Tom and Jerry/S1950E06 - Tom and Jerry in the Hollywood Bowl.mkv"},
// {"name": "The Framed Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E07 - The Framed Cat.mkv"},
// {"name": "Cue Ball Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E08 - Cue Ball Cat.mkv"},
// {"name": "Casanova Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E09 - Casanova Cat.mkv"},
// {"name": "Jerry And The Goldfish", "uri": "/home/anon/videos/Tom and Jerry/S1950E10 - Jerry And The Goldfish.mkv"},
// {"name": "Jerry's Cousin", "uri": "/home/anon/videos/Tom and Jerry/S1950E11 - Jerry's Cousin.mkv"},
// {"name": "Sleepy-Time Tom", "uri": "/home/anon/videos/Tom and Jerry/S1950E12 - Sleepy-Time Tom.mkv"},
// {"name": "His Mouse Friday", "uri": "/home/anon/videos/Tom and Jerry/S1950E13 - His Mouse Friday.mkv"},
// {"name": "Slicked-Up Pup", "uri": "/home/anon/videos/Tom and Jerry/S1950E14 - Slicked-Up Pup.mkv"},
// {"name": "Nit-Witty Kitty", "uri": "/home/anon/videos/Tom and Jerry/S1950E15 - Nit-Witty Kitty.mkv"},
// {"name": "Cat Napping", "uri": "/home/anon/videos/Tom and Jerry/S1950E16 - Cat Napping.mkv"},
// {"name": "The Flying Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E17 - The Flying Cat.mkv"},
// {"name": "The Duck Doctor", "uri": "/home/anon/videos/Tom and Jerry/S1950E18 - The Duck Doctor.mkv"},
// {"name": "The Two Mouseketeers", "uri": "/home/anon/videos/Tom and Jerry/S1950E19 - The Two Mouseketeers.mkv"},
// {"name": "Smitten Kitten", "uri": "/home/anon/videos/Tom and Jerry/S1950E20 - Smitten Kitten.mkv"},
// {"name": "Triplet Trouble", "uri": "/home/anon/videos/Tom and Jerry/S1950E21 - Triplet Trouble.mkv"},
// {"name": "Little Runaway", "uri": "/home/anon/videos/Tom and Jerry/S1950E22 - Little Runaway.mkv"},
// {"name": "Fit To Be Tied", "uri": "/home/anon/videos/Tom and Jerry/S1950E23 - Fit To Be Tied.mkv"},
// {"name": "Push-Button Kitty", "uri": "/home/anon/videos/Tom and Jerry/S1950E24 - Push-Button Kitty.mkv"},
// {"name": "Cruise Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E25 - Cruise Cat.mkv"},
// {"name": "The Dog House", "uri": "/home/anon/videos/Tom and Jerry/S1950E26 - The Dog House.mkv"},
// {"name": "The Missing Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1950E27 - The Missing Mouse.mkv"},
// {"name": "Jerry And Jumbo", "uri": "/home/anon/videos/Tom and Jerry/S1950E28 - Jerry And Jumbo.mkv"},
// {"name": "Johann Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1950E29 - Johann Mouse.mkv"},
// {"name": "That's My Pup!", "uri": "/home/anon/videos/Tom and Jerry/S1950E30 - That's My Pup!.mkv"},
// {"name": "Just Ducky", "uri": "/home/anon/videos/Tom and Jerry/S1950E31 - Just Ducky.mkv"},
// {"name": "Two Little Indians", "uri": "/home/anon/videos/Tom and Jerry/S1950E32 - Two Little Indians.mkv"},
// {"name": "Life With Tom", "uri": "/home/anon/videos/Tom and Jerry/S1950E33 - Life With Tom.mkv"},
// {"name": "Puppy Tale", "uri": "/home/anon/videos/Tom and Jerry/S1950E34 - Puppy Tale.mkv"},
// {"name": "Posse Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E35 - Posse Cat.mkv"},
// {"name": "Hic-cup Pup", "uri": "/home/anon/videos/Tom and Jerry/S1950E36 - Hic-cup Pup.mkv"},
// {"name": "Little School Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1950E37 - Little School Mouse.mkv"},
// {"name": "Baby Butch", "uri": "/home/anon/videos/Tom and Jerry/S1950E38 - Baby Butch.mkv"},
// {"name": "Mice Follies", "uri": "/home/anon/videos/Tom and Jerry/S1950E39 - Mice Follies.mkv"},
// {"name": "Neapolitan Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1950E40 - Neapolitan Mouse.mkv"},
// {"name": "Downhearted Duckling", "uri": "/home/anon/videos/Tom and Jerry/S1950E41 - Downhearted Duckling.mkv"},
// {"name": "Pet Peeve", "uri": "/home/anon/videos/Tom and Jerry/S1950E42 - Pet Peeve.mkv"},
// {"name": "Touché, Pussy Cat!", "uri": "/home/anon/videos/Tom and Jerry/S1950E43 - Touché, Pussy Cat!.mkv"},
// {"name": "Southbound Duckling", "uri": "/home/anon/videos/Tom and Jerry/S1950E44 - Southbound Duckling.mkv"},
// {"name": "Pup On A Picnic", "uri": "/home/anon/videos/Tom and Jerry/S1950E45 - Pup On A Picnic.mkv"},
// {"name": "Mouse For Sale", "uri": "/home/anon/videos/Tom and Jerry/S1950E46 - Mouse For Sale.mkv"},
// {"name": "Designs On Jerry", "uri": "/home/anon/videos/Tom and Jerry/S1950E47 - Designs On Jerry.mkv"},
// {"name": "Tom And Chérie", "uri": "/home/anon/videos/Tom and Jerry/S1950E48 - Tom And Chérie.mkv"},
// {"name": "Smarty Cat", "uri": "/home/anon/videos/Tom and Jerry/S1950E49 - Smarty Cat.mkv"},
// {"name": "Pecos Pest", "uri": "/home/anon/videos/Tom and Jerry/S1950E50 - Pecos Pest.mkv"},
// {"name": "That's My Mommy", "uri": "/home/anon/videos/Tom and Jerry/S1950E51 - That's My Mommy.mkv"},
// {"name": "The Flying Sorceress", "uri": "/home/anon/videos/Tom and Jerry/S1950E52 - The Flying Sorceress.mkv"},
// {"name": "The Egg And Jerry", "uri": "/home/anon/videos/Tom and Jerry/S1950E53 - The Egg And Jerry.mkv"},
// {"name": "Busy Buddies", "uri": "/home/anon/videos/Tom and Jerry/S1950E54 - Busy Buddies.mkv"},
// {"name": "Muscle Beach Tom", "uri": "/home/anon/videos/Tom and Jerry/S1950E55 - Muscle Beach Tom.mkv"},
// {"name": "Down Beat Bear", "uri": "/home/anon/videos/Tom and Jerry/S1950E56 - Down Beat Bear.mkv"},
// {"name": "Blue Cat Blues", "uri": "/home/anon/videos/Tom and Jerry/S1950E57 - Blue Cat Blues.mkv"},
// {"name": "Barbecue Brawl", "uri": "/home/anon/videos/Tom and Jerry/S1950E58 - Barbecue Brawl.mkv"},
// {"name": "Tops With Pops", "uri": "/home/anon/videos/Tom and Jerry/S1950E59 - Tops With Pops.mkv"},
// {"name": "Timid Tabby", "uri": "/home/anon/videos/Tom and Jerry/S1950E60 - Timid Tabby.mkv"},
// {"name": "Feedin' The Kiddie", "uri": "/home/anon/videos/Tom and Jerry/S1950E61 - Feedin' The Kiddie.mkv"},
// {"name": "Mucho Mouse", "uri": "/home/anon/videos/Tom and Jerry/S1950E62 - Mucho Mouse.mkv"},
// {"name": "Tom's Photo Finish", "uri": "/home/anon/videos/Tom and Jerry/S1950E63 - Tom's Photo Finish.mkv"},
// {"name": "Happy Go Ducky", "uri": "/home/anon/videos/Tom and Jerry/S1950E64 - Happy Go Ducky.mkv"},
// {"name": "Royal Cat Nap", "uri": "/home/anon/videos/Tom and Jerry/S1950E65 - Royal Cat Nap.mkv"},
// {"name": "The Vanishing Duck", "uri": "/home/anon/videos/Tom and Jerry/S1950E66 - The Vanishing Duck.mkv"},
// {"name": "Robin Hoodwinked", "uri": "/home/anon/videos/Tom and Jerry/S1950E67 - Robin Hoodwinked.mkv"},
// {"name": "Tot Watchers", "uri": "/home/anon/videos/Tom and Jerry/S1950E68 - Tot Watchers.mkv"},
// {"name": "Mouse into Space", "uri": "/home/anon/videos/Tom and Jerry/S1960E05 - Mouse into Space.mkv"},
// {"name": "Dicky Moe", "uri": "/home/anon/videos/Tom and Jerry/S1960E08 - Dicky Moe.mkv"},
// {"name": "Buddies Thicker Than Water", "uri": "/home/anon/videos/Tom and Jerry/S1960E12 - Buddies Thicker Than Water.mkv"},
// {"name": "The Cat Above and the Mouse Below", "uri": "/home/anon/videos/Tom and Jerry/S1960E15 - The Cat Above and the Mouse Below.mkv"},
// {"name": "Is There a Doctor in the Mouse？", "uri": "/home/anon/videos/Tom and Jerry/S1960E16 - Is There a Doctor in the Mouse？.mkv"},
// {"name": "Snowbody Loves Me", "uri": "/home/anon/videos/Tom and Jerry/S1960E18 - Snowbody Loves Me.mkv"},
// {"name": "Of Feline Bondage", "uri": "/home/anon/videos/Tom and Jerry/S1960E26 - Of Feline Bondage.mkv"},
// {"name": "The Cat's Me-Ouch", "uri": "/home/anon/videos/Tom and Jerry/S1960E28 - The Cat's Me-Ouch.mkv"},
// {"name": "The A-TOM-iNABLE Snowman", "uri": "/home/anon/videos/Tom and Jerry/S1960E36 - The A-TOM-iNABLE Snowman.mkv"},
// {"name": "Catty-Cornered", "uri": "/home/anon/videos/Tom and Jerry/S1960E37 - Catty-Cornered.mkv"},
// {"name": "The Mouse from H.U.N.G.E.R", "uri": "/home/anon/videos/Tom and Jerry/S1960E43 - The Mouse from H.U.N.G.E.R..mkv"}
